# attribute-map.yml
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress": "email"
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname": "last_name"
"http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname": "first_name"