# attribute-map.yml
<%= Rails.application.credentials.staging[:attribute_map_email] %>: "email"
<%= Rails.application.credentials.staging[:attribute_map_last_name] %>: "last_name"
<%= Rails.application.credentials.staging[:attribute_map_first_name] %>: "first_name"