<%= Rails.application.credentials.staging[:attribute_map_email] %>
<%= Rails.application.credentials.staging[:attribute_map_last_name] %>
<%= Rails.application.credentials.staging[:attribute_map_first_name] %>