default: &default
  host:     <%= COMPETITIONS_CONFIG[:database][:host] %>
  adapter:  <%= COMPETITIONS_CONFIG[:database][:adapter] %>
  database: <%= COMPETITIONS_CONFIG[:database][:database] %>
  username: <%= COMPETITIONS_CONFIG[:database][:username] %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :password) %>
test: &TEST
  <<: *default
development:
  <<: *default
alpha:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
