development:
  host:     <%= Rails.application.credentials.development[:host] %>
  adapter:  <%= Rails.application.credentials.development[:adapter] %>
  database: <%= Rails.application.credentials.development[:database] %>
  username: <%= Rails.application.credentials.development[:username] %>
  password: <%= Rails.application.credentials.development[:password] %>
alpha:
  host:     <%= Rails.application.credentials.alpha[:host] %>
  adapter:  <%= Rails.application.credentials.alpha[:adapter] %>
  database: <%= Rails.application.credentials.alpha[:database] %>
  username: <%= Rails.application.credentials.alpha[:username] %>
  password: <%= Rails.application.credentials.alpha[:password] %>
staging:
  host:     <%= Rails.application.credentials.staging[:host] %>
  adapter:  <%= Rails.application.credentials.staging[:adapter] %>
  database: <%= Rails.application.credentials.staging[:database] %>
  username: <%= Rails.application.credentials.staging[:username] %>
  password: <%= Rails.application.credentials.staging[:password] %>
