development:
  secret_key_base:
  database_password:
  aws_access_key_id:
  aws_secret_access_key:
  smtp_settings: { address:                '',
                   port:                   ,
                   domain:                 '',
                   user_name:              '',
                   password:               '',
                   authentication:         '',
                   enable_starttls_auto:   ,
                   ssl:                     }
  idp_cert:
test:
  secret_key_base:
  database_password:
  aws_access_key_id:
  aws_secret_access_key:
  smtp_settings: { address:                '',
                   port:                   ,
                   domain:                 '',
                   user_name:              '',
                   password:               '',
                   authentication:         '',
                   enable_starttls_auto:   ,
                   ssl:                     }
  idp_cert: